# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_xgboost_gpu <- function(train, train_labels, valid, test, mode) {
    .Call(`_fastImputeGPU_cpp_xgboost_gpu`, train, train_labels, valid, test, mode)
}

