// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_xgboost_gpu
List cpp_xgboost_gpu(SEXP train, SEXP train_labels, SEXP valid, SEXP test, SEXP mode);
RcppExport SEXP _fastImputeGPU_cpp_xgboost_gpu(SEXP trainSEXP, SEXP train_labelsSEXP, SEXP validSEXP, SEXP testSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type train(trainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type train_labels(train_labelsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type valid(validSEXP);
    Rcpp::traits::input_parameter< SEXP >::type test(testSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xgboost_gpu(train, train_labels, valid, test, mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastImputeGPU_cpp_xgboost_gpu", (DL_FUNC) &_fastImputeGPU_cpp_xgboost_gpu, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastImputeGPU(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
